<a href="https://colab.research.google.com/github/abulhasanat/MachineLearning/blob/master/pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch

In [13]:
d=torch.randn(4,5)
d

tensor([[-0.0723,  0.4611, -1.2124,  0.1146,  0.4469],
        [-0.5945,  1.2353, -0.3295, -0.3218, -0.0902],
        [ 0.6200,  0.5901,  0.0151, -1.0755,  0.1909],
        [-1.1024, -0.2545, -0.4689,  0.5435, -0.0036]])

In [18]:
torch.argmin(d,dim=1)

tensor([2, 0, 3, 0])

In [15]:
torch.argmin(d)

tensor(2)

In [16]:
torch.argmax(d)

tensor(6)

In [6]:
a=torch.randn(4,4)
print (a)

tensor([[-1.7681, -0.0047, -0.9644,  1.7289],
        [-1.0738,  0.7602, -0.3899, -1.7726],
        [ 0.3045, -2.2884, -1.4322, -1.6826],
        [ 0.7659,  1.0113,  1.5058,  0.8983]])


In [7]:
indices=torch.LongTensor([0,2])

In [8]:
indices

tensor([0, 2])

In [9]:
torch.index_select(a,0,indices)

tensor([[-1.7681, -0.0047, -0.9644,  1.7289],
        [ 0.3045, -2.2884, -1.4322, -1.6826]])

In [10]:
torch.index_select(a,1,indices)

tensor([[-1.7681, -0.9644],
        [-1.0738, -0.3899],
        [ 0.3045, -1.4322],
        [ 0.7659,  1.5058]])

In [15]:
torch.split(torch.tensor([12,21,34,45,21,43,45,23,56]),4)

(tensor([12, 21, 34, 45]), tensor([21, 43, 45, 23]), tensor([56]))